local no_colour=nil
vim.api.nvim_set_hl(0, 'String'             , { bg=no_colour, fg='#AFD7AF', } )
vim.api.nvim_set_hl(0, 'Comment'            , { bg=no_colour, fg='#87AFD7', } )
vim.api.nvim_set_hl(0, 'Constant'           , { bg=no_colour, fg='#AFD7AF', } )
vim.api.nvim_set_hl(0, 'Special'            , { bg=no_colour, fg='#875F00', } )
vim.api.nvim_set_hl(0, 'Identifier'         , { bg=no_colour, fg='#FFFFFF', } )
vim.api.nvim_set_hl(0, 'Statement'          , { bg=no_colour, fg='#FFFF87', } )
vim.api.nvim_set_hl(0, 'PreProc'            , { bg=no_colour, fg='#FF87FF', } )
vim.api.nvim_set_hl(0, 'type'               , { bg=no_colour, fg='#D78787', } )
vim.api.nvim_set_hl(0, 'Underlined'         , { bg=no_colour, fg=no_colour,  underline=true } )
vim.api.nvim_set_hl(0, 'Ignore'             , { bg=no_colour, fg=no_colour,    } )
vim.api.nvim_set_hl(0, 'Normal'             , { bg=no_colour, fg='#FFFFFF', } )
vim.api.nvim_set_hl(0, 'NonText'            , { bg=no_colour, fg='#FFFFFF', } )
vim.api.nvim_set_hl(0, 'ErrorMsg'           , { bg='#0000FF', fg='#FFFFFF', } )
vim.api.nvim_set_hl(0, 'Visual'             , { bg='#3A3A3A', fg=no_colour, } )
vim.api.nvim_set_hl(0, 'Todo'               , { bg=no_colour, fg='#AF87AF', bold=true } )
vim.api.nvim_set_hl(0, 'Keyword'            , { bg=no_colour, fg='#AF87AF', bold=true } )
vim.api.nvim_set_hl(0, 'Search'             , { bg='#000080', fg='#FFFFFF', underline=true } )
vim.api.nvim_set_hl(0, 'IncSearch'          , { bg='#767676', fg='#000080', underline=true } )
vim.api.nvim_set_hl(0, 'SpecialKey'         , { bg=no_colour, fg=no_colour,    } )
vim.api.nvim_set_hl(0, 'Directory'          , { bg=no_colour, fg='#5F87D7', bold=true } )
vim.api.nvim_set_hl(0, 'Title'              , { bg='#3A3A3A', fg=no_colour, bold=true } )
vim.api.nvim_set_hl(0, 'WarningMsg'         , { bg='#000080', fg=no_colour, } )
vim.api.nvim_set_hl(0, 'WildMenu'           , { bg='#000080', fg=no_colour, } )
vim.api.nvim_set_hl(0, 'ModeMsg'            , { bg='#767676', fg=no_colour, } )
vim.api.nvim_set_hl(0, 'MoreMsg'            , { bg='#767676', fg=no_colour, } )
vim.api.nvim_set_hl(0, 'Question'           , { bg='#767676', fg=no_colour, } )
vim.api.nvim_set_hl(0, 'Folded'             , { bg=no_colour, fg='#3A3A3A', bold=true } )
vim.api.nvim_set_hl(0, 'FoldColumn'         , { bg=no_colour, fg='#3A3A3A', bold=true } )
vim.api.nvim_set_hl(0, 'LineNr'             , { bg=no_colour, fg='#5F5FFF', } )
vim.api.nvim_set_hl(0, 'CursorLineNr'       , { bg='#1C1C1C', fg='#87FF87', bold=true } )
vim.api.nvim_set_hl(0, 'CursorLine'         , { bg='#1C1C1C', fg=no_colour, } )
vim.api.nvim_set_hl(0, 'DiffAdd'            , { bg='#000080', fg=no_colour, } )
vim.api.nvim_set_hl(0, 'DiffChange'         , { bg='#FF87FF', fg=no_colour, } )
vim.api.nvim_set_hl(0, 'DiffDelete'         , { bg='#00FFFF', fg='#0000FF', } )
vim.api.nvim_set_hl(0, 'DiffText'           , { bg='#D70000', fg=no_colour, bold=true } )
vim.api.nvim_set_hl(0, 'Cursor'             , { bg='#FFFF87', fg=no_colour, } )
vim.api.nvim_set_hl(0, 'lCursor'            , { bg='#FFFFFF', fg=no_colour, } )
vim.api.nvim_set_hl(0, 'StatusLine'         , { bg=no_colour, fg='#87FF00', underline=true } )
vim.api.nvim_set_hl(0, 'StatusLineNC'       , { bg=no_colour, fg='#FFFFFF', underline=true } )
vim.api.nvim_set_hl(0, 'VertSplit'          , { bg=no_colour, fg='#008000', } )
vim.api.nvim_set_hl(0, 'Pmenu'              , { bg='#1C1C1C', fg='#FFFFFF', } )
vim.api.nvim_set_hl(0, 'PmenuSel'           , { bg='#585858', fg='#008000', } )
vim.api.nvim_set_hl(0, 'PmenuSbar'          , { bg=no_colour, fg='#5F87AF', underline=true } )
vim.api.nvim_set_hl(0, 'PmenuThumb'         , { bg=no_colour, fg=no_colour, } )
vim.api.nvim_set_hl(0, 'NvimTreeRootFolder' , { bg=no_colour, fg='#AFAF00', bold=true } )
vim.api.nvim_set_hl(0, 'NvimTreeCursorline' , { bg='#303030', fg=no_colour, bold=true } )
vim.api.nvim_set_hl(0, 'NvimTreeOpenedFile' , { bg=no_colour, fg='#AFD787', bold=true } )
vim.api.nvim_set_hl(0, 'NvimTreeOpenedHL'   , { bg=no_colour, fg='#AFD787', bold=true } )
vim.api.nvim_set_hl(0, 'TermCursor'         , { bg='#D70000', fg=no_colour, } )
vim.api.nvim_set_hl(0, 'TermCursorNC'       , { bg=no_colour, fg='#D70000', } )
