local set_color_scheme = function()
  vim.api.nvim_set_hl(0, 'String'               , { ctermfg=151           , ctermbg='NONE'       , cterm={} } )
  vim.api.nvim_set_hl(0, 'Comment'              , { ctermfg=110           , ctermbg='NONE'       , cterm={} } )
  vim.api.nvim_set_hl(0, 'Constant'             , { ctermfg=151           , ctermbg='NONE'       , cterm={} } )
  vim.api.nvim_set_hl(0, 'Special'              , { ctermfg='brown'       , ctermbg='NONE'       , cterm={} } )
  vim.api.nvim_set_hl(0, 'Identifier'           , { ctermfg='white'       , ctermbg='NONE'       , cterm={} } )
  vim.api.nvim_set_hl(0, 'Statement'            , { ctermfg='yellow'      , ctermbg='NONE'       , cterm={} } )
  vim.api.nvim_set_hl(0, 'PreProc'              , { ctermfg='magenta'     , ctermbg='NONE'       , cterm={} } )
  vim.api.nvim_set_hl(0, 'type'                 , { ctermfg=174           , ctermbg='NONE'       , cterm={} } )
  vim.api.nvim_set_hl(0, 'Underlined'           , { ctermfg='NONE'        , ctermbg='NONE'       , cterm={underline=true} } )
  vim.api.nvim_set_hl(0, 'Ignore'               , { ctermfg='NONE'        , ctermbg='NONE'       , cterm={} } )

  vim.api.nvim_set_hl(0, 'Normal'               , { ctermfg='white'       , ctermbg='NONE'       , cterm={} } )
  vim.api.nvim_set_hl(0, 'NonText'              , { ctermfg='NONE'        , ctermbg='NONE'       , cterm={} } )
  vim.api.nvim_set_hl(0, 'ErrorMsg'             , { ctermfg='white'       , ctermbg='blue'       , cterm={} } )
  vim.api.nvim_set_hl(0, 'Visual'               , { ctermfg='NONE'        , ctermbg=237          , cterm={} } )
  vim.api.nvim_set_hl(0, 'Todo'                 , { ctermfg='red'         , ctermbg='darkblue'   , cterm={} } )
  vim.api.nvim_set_hl(0, 'Search'               , { ctermfg='white'       , ctermbg='darkblue'   , cterm={underline=true} } )
  vim.api.nvim_set_hl(0, 'IncSearch'            , { ctermfg='darkblue'    , ctermbg='gray'       , cterm={underline=true} } )

  vim.api.nvim_set_hl(0, 'SpecialKey'           , { ctermfg='NONE'        , ctermbg='NONE'       , cterm={} } )
  vim.api.nvim_set_hl(0, 'Directory'            , { ctermfg='NONE'        , ctermbg='blue'       , cterm={} } )
  vim.api.nvim_set_hl(0, 'Title'                , { ctermfg='NONE'        , ctermbg=237          , cterm={bold=true} } )
  vim.api.nvim_set_hl(0, 'WarningMsg'           , { ctermfg='NONE'        , ctermbg='darkblue'   , cterm={} } )
  vim.api.nvim_set_hl(0, 'WildMenu'             , { ctermfg='NONE'        , ctermbg='darkblue'   , cterm={} } )
  vim.api.nvim_set_hl(0, 'ModeMsg'              , { ctermfg='NONE'        , ctermbg='gray'       , cterm={} } )
  vim.api.nvim_set_hl(0, 'MoreMsg'              , { ctermfg='NONE'        , ctermbg='gray'       , cterm={} } )
  vim.api.nvim_set_hl(0, 'Question'             , { ctermfg='NONE'        , ctermbg='gray'       , cterm={} } )

  vim.api.nvim_set_hl(0, 'Folded'               , { ctermfg='darkgrey'    , ctermbg='NONE'       , cterm={bold=true} } )
  vim.api.nvim_set_hl(0, 'FoldColumn'           , { ctermfg='darkgrey'    , ctermbg='NONE'       , cterm={bold=true} } )
  vim.api.nvim_set_hl(0, 'LineNr'               , { ctermfg='darkyellow'  , ctermbg='NONE'       , cterm={} } )
  vim.api.nvim_set_hl(0, 'CursorLineNr'         , { ctermfg='green'       , ctermbg=234          , cterm={} } )
  vim.api.nvim_set_hl(0, 'CursorLine'           , { ctermfg='NONE'        , ctermbg=234          , cterm={} } )

  vim.api.nvim_set_hl(0, 'DiffAdd'              , { ctermfg='NONE'        , ctermbg='darkblue'   , cterm={} } )
  vim.api.nvim_set_hl(0, 'DiffChange'           , { ctermfg='NONE'        , ctermbg='magenta'    , cterm={} } )
  vim.api.nvim_set_hl(0, 'DiffDelete'           , { ctermfg='blue'        , ctermbg='cyan'       , cterm={} } )
  vim.api.nvim_set_hl(0, 'DiffText'             , { ctermfg='NONE'        , ctermbg='red'        , cterm={bold=true} } )

  vim.api.nvim_set_hl(0, 'Cursor'               , { ctermfg='black'       , ctermbg='yellow'     , cterm={} } )
  vim.api.nvim_set_hl(0, 'lCursor'              , { ctermfg='black'       , ctermbg='white'      , cterm={} } )

  vim.api.nvim_set_hl(0, 'StatusLine'           , { ctermfg='lightgreen'  , ctermbg='NONE'       , cterm={underline=true} } )
  vim.api.nvim_set_hl(0, 'StatusLineNC'         , { ctermfg='white'       , ctermbg='NONE'       , cterm={underline=true} } )
  vim.api.nvim_set_hl(0, 'VertSplit'            , { ctermfg='green'       , ctermbg='NONE'       , cterm={} } )

  vim.api.nvim_set_hl(0, 'Pmenu'                , { ctermfg='white'       , ctermbg=234          , cterm={} } )
  vim.api.nvim_set_hl(0, 'PmenuSel'             , { ctermfg='green'       , ctermbg=240          , cterm={} } )
  vim.api.nvim_set_hl(0, 'PmenuSbar'            , { ctermfg=67            , ctermbg='NONE'       , cterm={underline=true} } )
  vim.api.nvim_set_hl(0, 'PmenuThumb'           , { ctermfg='NONE'        , ctermbg='NONE'       , cterm={} } )

  vim.api.nvim_set_hl(0, 'NvimTreeRootFolder'      , { ctermfg=142         , ctermbg='NONE'       , cterm={bold=true} } )
  vim.api.nvim_set_hl(0, 'NvimTreeCursorline'      , { ctermfg='NONE'    , ctermbg=236          , cterm={bold=true} } )
  vim.api.nvim_set_hl(0, 'NvimTreeOpenedFile'      , { ctermfg=150    , ctermbg='NONE'       , cterm={bold=true} } )
  vim.api.nvim_set_hl(0, 'NvimTreeFolderName'      , { ctermfg=68         , ctermbg='NONE'       , cterm={bold=true} } )
  vim.api.nvim_set_hl(0, 'NvimTreeOpenedFolderName', { ctermfg=68         , ctermbg='NONE'       , cterm={bold=true} } )
  vim.api.nvim_set_hl(0, 'NvimTreeEmptyFolderName' , { ctermfg=68         , ctermbg='NONE'       , cterm={bold=true} } )

  vim.api.nvim_set_hl(0, 'TermCursor'           , { ctermfg='NONE'         , ctermbg='red'       , cterm={} } )
  vim.api.nvim_set_hl(0, 'TermCursorNC'         , { ctermfg='red'         , ctermbg='NONE'       , cterm={} } )
end

set_color_scheme()

--vim.api.nvim_create_autocmd('BufNew', { pattern='*', callback=set_color_scheme } )
